name: flutter_news_notif5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  http: ^1.1.2
  webview_flutter: ^3.0.4
  provider: ^6.1.1
  # android_alarm_manager_plus: ^3.0.4
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.2
  flutter_local_notifications: ^11.0.0
  rxdart: ^0.27.5

flutter:
  uses-material-design: true
